feat: add test env vars

diff --git a/.github/workflows/build-and-deploy.yml b/.github/workflows/build-and-deploy.yml
--- a/.github/workflows/build-and-deploy.yml
+++ b/.github/workflows/build-and-deploy.yml
@@ -16,6 +16,22 @@ jobs:
       - name: Run Version Check
         uses: ./.github/actions/version-check
 
+      - name: Set Environment Variables
+        run: |
+          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
+            echo "ENV_NAME=prod" >> $GITHUB_ENV
+            echo "KUBE_CONFIG=${{ secrets.KUBE_CONFIG_PROD }}" >> $GITHUB_ENV
+            echo "VALUES_FILE=./helm/environment/prod.values.yaml" >> $GITHUB_ENV
+          elif [[ "${{ github.ref }}" == "refs/heads/test" ]]; then
+            echo "ENV_NAME=test" >> $GITHUB_ENV
+            echo "KUBE_CONFIG=${{ secrets.KUBE_CONFIG_TEST }}" >> $GITHUB_ENV
+            echo "VALUES_FILE=./helm/environment/test.values.yaml" >> $GITHUB_ENV
+          else
+            echo "ENV_NAME=dev" >> $GITHUB_ENV
+            echo "KUBE_CONFIG=${{ secrets.KUBE_CONFIG_DEV }}" >> $GITHUB_ENV
+            echo "VALUES_FILE=./helm/environment/dev.values.yaml" >> $GITHUB_ENV
+          fi
+
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v3
         with:
@@ -44,13 +60,13 @@ jobs:
       - name: Set up kubectl
         run: |
           mkdir ${HOME}/.kube
-          echo ${{ secrets.KUBE_CONFIG_DEV }} | base64 --decode > ${HOME}/.kube/config
+          echo "${{ env.KUBE_CONFIG }}" | base64 --decode > ${HOME}/.kube/config
 
           echo "Checking current context..."
           kubectl config current-context || { echo "Error: No valid Kubernetes context found."; exit 1; }
 
           # Check cluster info
-          kubectl cluster-info || { echo "Error: Unable to reach Kubernetes API. Check KUBE_CONFIG_DEV."; exit 1; }
+          kubectl cluster-info || { echo "Error: Unable to reach Kubernetes API. Check KUBE_CONFIG."; exit 1; }
 
       - name: Update ECR Secret in Kubernetes
         run: |
@@ -64,6 +80,6 @@ jobs:
         env:
           IMAGE_TAG: ${{ env.IMAGE_TAG }}
         run: |
-          sed -i "s|vIMAGE_TAG|$IMAGE_TAG|g" ./helm/environment/dev.values.yaml
+          sed -i "s|vIMAGE_TAG|$IMAGE_TAG|g" ${{ env.VALUES_FILE }}
           helm ls
-          helm upgrade --install biletim-backend ./helm -f ./helm/values.yaml -f ./helm/environment/dev.values.yaml
+          helm upgrade --install biletim-backend ./helm -f ./helm/values.yaml -f ${{ env.VALUES_FILE }}
